services:
  - type: web
    name: vestiventa
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: vestiventa
          property: connectionString
      - key: DISABLE_DATABASE_ENVIRONMENT_CHECK
        value: "1"
      - key: PGSSLMODE
        value: "prefer"
    plan: free
    numInstances: 1
    regions:
      - sfo
    healthCheckPath: /up

  - type: postgres
    name: vestiventa
    plan: free
    databaseName: vestiventa_production
    user: vestiventa_user
    ipAllowList:
      - 0.0.0.0/0