default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vestiventa_development
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: vestiventa_test
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  sslmode: prefer
  sslcompression: 0
  ssl_min_protocol_version: 'TLSv1.2'
  sslrootcert: /etc/ssl/certs/ca-certificates.crt