default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vestiventa_development
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: vestiventa_test
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  sslmode: verify-full
  sslrootcert: /etc/ssl/certs/ca-certificates.crt
  variables:
    sslmode: verify-full