default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vestiventa_development
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: vestiventa_test
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

  primary_replica:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    replica: true

cable:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

queue:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

cache:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>